config/routes.rb
Rails.application.routes.draw do
  resources :lists

  root 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
	validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @search = List.search(params[:q])
    @lists = @search.result
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :category, :color, :size, :price, :priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wishlist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for (@list) do |f| %>
<%= f.error_notification %>
<%= f.input :name %>
<%= f.input :price, hint: "prices should be in US dollar" %>
<%= f.input :category, label: "Category" %>
<%= f.input :color %>
<%= f.input :size, hint: "size small-large, or n/s" %>
<%= f.input :priority, collection: 1..5, as: :radio_buttons %>
<%= f.button :submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All the things I want</h1>


<%= search_form_for @search do |f| %>
<div class="field">
<%= f.label :name_cont, "Name Contains" %>
<%= f.text_field :name_cont %>
</div>

<div class="field">
<%= f.label :price_gteq, "Price Between" %>
<%= f.text_field :price_gteq %>
<%= f.label :price_lteq, "and" %>
<%= f.text_field :price_lteq %>
</div>

<div class="actions">
<%= f.submit "Search" %>
</div>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= sort_link @search, :name,  "Name" %></th>
      <th><%= sort_link @search, :category, "Category" %></th>
      <th><%= sort_link @search, :color, "Color" %></th>
      <th><%= sort_link @search, :size, "Size" %></th>
      <th><%= sort_link @search, :price, "Price" %></th>
      <th><%= sort_link @search, :priority, "Priority" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= list.category %></td>
        <td><%= list.color %></td>
        <td><%= list.size %></td>
        <td><%= list.price %></td>
        <td><%= list.priority %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @list.category %>
</p>

<p>
  <strong>Color:</strong>
  <%= @list.color %>
</p>

<p>
  <strong>Size:</strong>
  <%= @list.size %>
</p>

<p>
  <strong>Price:</strong>
  <%= @list.price %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @list.priority %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>